@extends('layouts.admin-app')

@section('title', 'Payments')

@section('page-css')
<style>
    .page-heading { max-width: 890px; margin-bottom: 26px; } .page-heading h1 { margin: 0; font-size: 31px; letter-spacing: -.7px; } .page-heading p { margin: 9px 0 0; color: #4d5853; font-size: 16px; }.filter-card,.payment-card { max-width: 890px; background: #fff; border-radius: 9px; box-shadow: 0 2px 9px rgba(20,48,36,.05); }.filter-card { display: flex; align-items: end; gap: 16px; margin-bottom: 22px; padding: 28px 32px; }.filter-group { display:grid; gap:8px; }.filter-group label { font-size:12px; font-weight:750; letter-spacing:.45px; color:#44534c; }.filter-group input,.filter-group select { height:41px; min-width:170px; padding:0 12px; border:1px solid #c7d2cc; border-radius:7px; font:inherit; font-size:14px; }.filter-group select { min-width:145px; }.apply { height:41px; padding:0 21px; border:0; border-radius:6px; background:#dfe2e1; color:#44534c; font-weight:700; cursor:pointer; }.payment-card { overflow:hidden; }.payment-card h2 { margin:0; padding:34px 32px 18px; font-size:18px; }.payment-table { width:100%; border-collapse:collapse; }.payment-table th { padding:15px 24px; background:#f1f3f4; color:#44534c; font-size:12px; text-align:left; }.payment-table td { padding:18px 24px; border-bottom:1px solid #e7ebe9; font-size:14px; }.payment-id { color:#38433e; }.sale-id { color:#7b8580; }.status { padding:4px 9px; border-radius:4px; font-size:12px; }.paid { color:#167658; background:#d9f4e9; }.pending { color:#59625e; background:#ebedef; }.unpaid { color:#b42318; background:#fee4e2; }.footer { display:flex; justify-content:space-between; align-items:center; padding:16px 24px; color:#58655e; font-size:13px; }.pages { display:flex; gap:8px; }.pages span { display:grid; width:32px; height:32px; place-items:center; border:1px solid #cbd6d0; border-radius:4px; }.pages .selected { color:#00805e; border-color:#00805e; } @media(max-width:850px){.filter-card,.payment-card{overflow-x:auto}.filter-card{min-width:710px}.payment-table{min-width:820px}} @media(max-width:560px){.page-heading h1{font-size:27px}}
</style>
@endsection

@section('content')
<div class="page-heading"><h1>Payments</h1><p>Manage and track all transaction records.</p></div><form class="filter-card" method="GET" action="{{ route('admin.payments.index') }}"><div class="filter-group"><label for="payment-search">Search Customer or ID</label><input id="payment-search" name="search" value="{{ $filters['search'] }}" placeholder="e.g. PAY-0012 or John Doe"></div><div class="filter-group"><label for="payment-status">Status</label><select id="payment-status" name="status"><option value="">All Statuses</option><option value="paid" @selected($filters['status'] === 'paid')>Paid</option><option value="pending" @selected($filters['status'] === 'pending')>Pending</option><option value="unpaid" @selected($filters['status'] === 'unpaid')>Unpaid</option></select></div><button class="apply" type="submit">Apply</button></form><section class="payment-card"><h2>Transaction Records</h2><table class="payment-table"><thead><tr><th>Payment ID</th><th>Sale ID</th><th>Customer</th><th>Amount</th><th>Method</th><th>Status</th><th>Date</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td class="payment-id">{{ $payment->payment_id }}</td><td class="sale-id">{{ $payment->sale_id }}</td><td>{{ $payment->customer_name }}</td><td>${{ number_format($payment->amount, 2) }}</td><td>{{ $payment->method }}</td><td><span class="status {{ $payment->status }}">{{ ucfirst($payment->status) }}</span></td><td>{{ \Carbon\Carbon::parse($payment->date)->format('M d, Y') }}<div class="sale-id" style="margin-top:4px">{{ $payment->time }}</div></td></tr>@empty<tr><td colspan="7" style="padding:34px;text-align:center;color:#66716b">No payment records match your filters.</td></tr>@endforelse</tbody></table><div class="footer"><span>Showing {{ $pagination['from'] }} to {{ $pagination['to'] }} of {{ $pagination['total'] }} entries</span><div class="pages"><span>‹</span><span class="selected">1</span><span>2</span><span>3</span><span>›</span></div></div></section>
@endsection
